### ISSUE TITLE
The CLI does not give the prompt back

### ISSUE THREAD

**Issue by jacobotoll** [hubiinetwork/nahmii-cli#30]
Version: 1.0.0-beta.6

How to reproduce:
1.- run (any command) `nahmii show balance`
2.- will provide you with, for instance, the following output; `{"TT1":"34.96497","ETH":"16.993"}`
3.- then the CLI does not give you the prompt back giving the impression of "waiting for something". You need to (in mac) "Control + z" to stop the execution and get the prompt back to be able to run the next command

**Comment by jonbern** [comment]
This is cause by the token auto updater in the SDK, which is used to refresh the access token behind the scenes. What happens if that the SDK uses a `setInterval` function, which in regular intervals refreshes the access token. 

The problem is that node will not end the process when there is an active `setInterval` function running. 

To fix the problem, it's possible to explicitly invoke the `stopUpdate()` on the `nahmiiProvider`. Alternatively, we can wrap this behaviour in a reusable helper function that can be used by all the commands of the CLI, which automatically will run the `stopUpdate` function on completion.

**Comment by morfj** [comment]
It would be cool if we could hook into the execution chain og yargs with a "middleware" and stop the token updating that way.

**Comment by morfj** [comment]
Unfortunately the middleware in YARGS is "additive" so does not support interception/wrapping of inputs and outputs. :( had to do it "the hard way".
